// generated by mBlock5 for mBot
// codes make you happy

/*
	--todo--
	->movement und rotation fertig
	->nur noch bedingungen wann wie gefahren wird
	->move+delay ist autom. coord update dabei
	->rotation beinhaltet schon beides
*/

#include <MeMCore.h>
#include <Arduino.h>
#include <Wire.h>
#include <SoftwareSerial.h>
#include <cmath.h>

MeLightSensor lightsensor_6(6);
MeDCMotor motor_9(9);
MeDCMotor motor_10(10);
MeLineFollower linefollower_2(2);
MeUltrasonicSensor ultrasonic_3(3);
double currentTime = 0;
double lastTime = 0;
MeIR ir;
MeLEDMatrix ledMtx_1(1);

float k = 0;
int PI = 3.1415;

struct move_param{
	int forward = 1;
	int backward = 2;
	int turnLeft = 3;
	int turnRight =4;
	int speed=255;
	int engine_speed_coeff = 0;
	int diameter = 0;
	float wheelbase = 0;
};

struct coordinate{
	float x=0;
	float y=0;
	float phi = 0; //start in x
};



void move(const int dir, int speed) {
  int leftSpeed = 0;
  int rightSpeed = 0;
  if(dir == 1) {
    leftSpeed = speed;
    rightSpeed = speed;
  } else if(dir == 2) {
    leftSpeed = -speed;
    rightSpeed = -speed;
  } else if(dir == 3) {
    leftSpeed = -speed;
    rightSpeed = speed;
  } else if(dir == 4) {
    leftSpeed = speed;
    rightSpeed = -speed;
  }
  motor_9.run((9) == M1 ? -(leftSpeed) : (leftSpeed));
  motor_10.run((10) == M1 ? -(rightSpeed) : (rightSpeed));
}


void _delay(float seconds, move_param& param, coordinate& coord, bool CoordUpdate) {
  long endTime = millis() + seconds * 1000;
  while(millis() < endTime) _loop();
	//update coord
	if(CoordUpdate){
		coord.x += 2*PI*param.speed*param.engine_speed_coeff*seconds*std::cos(coord.phi)*(param.diameter/2);// s = v*t = 2pi n * t
		coord.y += 2*PI*param.speed*param.engine_speed_coeff*seconds*std::sin(coord.phi)*(param.diameter/2);
	}
}

void rotate_bot(move_param &param, coordinate & coord, float phi){ // phi in grad
	param.phi += phi;
	float theta = phi*(PI/180);
	float t = (param.wheelbase*theta)/(param.speed*param.engine_speed_coeff*2*PI*(param.diameter/2)) // t = wb*theta/n*2*pi*r
	if(phi>0){
		move(param.turnLeft, param.speed);
	}if(phi<0){
		move(param.turnRight, param.speed);
	}
	_delay(t, param, coord, false);

}

double getLastTime(){
  return currentTime = millis() / 1000.0 - lastTime;
}



void setup() {
  ir.begin();
  ledMtx_1.setColorIndex(1);
  ledMtx_1.setBrightness(6);
  if(lightsensor_6.read() == 1.000000){

    move(1, 50 / 100.0 * 255);
    _delay(1);
    move(1, 0);

  }
  if(linefollower_2.readSensors() == 2.000000){

    move(2, 50 / 100.0 * 255);
    _delay(1);
    move(2, 0);

  }
  if(ultrasonic_3.distanceCm() < 3){

    move(3, 50 / 100.0 * 255);
    _delay(1);
    move(3, 0);

  }
  if(getLastTime() == 4.000000){
    ir.sendString("hello");
    ledMtx_1.drawStr(0, 0 + 7, String("hello").c_str());
    motor_9.run(0);
    motor_10.run(0);

    motor_9.run(-1 * 50/100.0*255);
    motor_10.run(50/100.0*255);

  }

}

void _loop() {
}

void loop() {
  _loop();
}

